const mongoose = require('mongoose');

/**
 * DiscountCode — a single-use, time-limited token generated by approved staff.
 * TTL index auto-deletes expired unused codes after 24 h to keep collection lean.
 */
const discountCodeSchema = new mongoose.Schema(
  {
    code:            { type: String, required: true, unique: true, uppercase: true },
    storeId:         { type: mongoose.Schema.Types.ObjectId, ref: 'Store', required: true },
    generatedBy:     { type: mongoose.Schema.Types.ObjectId, ref: 'User',  required: true },
    generatedByName: { type: String, required: true },

    discountPercent: { type: Number, required: true, min: 0, max: 100 },

    expiresAt: { type: Date, required: true },
    isUsed:    { type: Boolean, default: false },
    isRevoked: { type: Boolean, default: false },

    // Filled when the code is consumed by createOrder
    usedAt:       { type: Date },
    usedByOrder:  { type: mongoose.Schema.Types.ObjectId, ref: 'Order' },
  },
  { timestamps: true }
);

discountCodeSchema.index({ storeId: 1, isUsed: 1 });
// TTL: MongoDB removes expired+unused codes 24 h after expiresAt
discountCodeSchema.index({ expiresAt: 1 }, { expireAfterSeconds: 86400 });

module.exports = mongoose.model('DiscountCode', discountCodeSchema);
